apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo-legacy
  namespace: apps
spec:
  releaseName: podinfo-legacy
  chart:
    spec:
      chart: podinfo
      sourceRef:
        kind: HelmRepository
        name: podinfo
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3
  # Default values
  # https://github.com/stefanprodan/podinfo/blob/master/charts/podinfo/values.yaml
  values:
    image:
      tag: 5.2.1
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: traefik
        traefik.ingress.kubernetes.io/router.middlewares: apps-podinfo-legacy-trailing-slash@kubernetescrd,apps-podinfo-legacy-path-rewrite@kubernetescrd
      hosts:
        - host: raspberrypi.local
          paths:
            - path: /legacy
              pathType: ImplementationSpecific
