name: Build & Deploy

on:
  push:
    branches:
      - "main"
    tags:
      - "v*"

jobs:
  deploy:
    name: Deploy 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: [dev, stg, prd]
    environment: ${{ matrix.env }}
    steps:
      - env: 	
          ENV: ${{ matrix.env }}
        run: echo $ENV
      - name : machine echo env
        env : { CONTENT : "${{ toJson(env) }}" }
        run : "echo $CONTENT"
      - name : machine echo secrets
        env : { CONTENT : "${{ toJson(secrets) }}" }
        run : "echo $CONTENT"
      - name : machine echo github
        env : { CONTENT : "${{ toJson(github) }}" }
        run : "echo $CONTENT"
      - name : machine echo runner
        env : { CONTENT : "${{ toJson(runner) }}" }
        run : "echo $CONTENT"
      - name : machine echo job
        env : { CONTENT : "${{ toJson(job) }}" }
        run : "echo $CONTENT"
      - name : machine echo strategy
        env : { CONTENT : "${{ toJson(strategy) }}" }
        run : "echo $CONTENT"
      - name : machine echo matrix
        env : { CONTENT : "${{ toJson(matrix) }}" }
        run : "echo $CONTENT"
      - name : machine echo steps
        env : { CONTENT : "${{ toJson(steps) }}" }
        run : "echo $CONTENT"
