name: Build & Deploy

on:
  push:
    branches:
      - "main"
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Prepare
        id: prep
        run: |
          VERSION=${GITHUB_SHA::8}
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF/refs\/tags\//}
          fi
          echo ::set-output name=BUILD_DATE::$(date -u +'%Y-%m-%dT%H:%M:%SZ')
          echo ::set-output name=VERSION::${VERSION}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: fabsrc/sandbox:${{ steps.prep.outputs.VERSION }}
          file: ./Dockerfile
      - name: Test
        run: docker run --rm fabsrc/sandbox:${{ steps.prep.outputs.VERSION }}

  deploy_test:
    runs-on: ubuntu-latest
    if: contains(github.ref, 'heads')
    needs: ["build"]
    name: Deploy Test
    environment: test
    steps:
      - run: echo "Deploy Test"

  deploy_dev:
    runs-on: ubuntu-latest
    if: contains(github.ref, 'tags')
    needs: ["build"]
    name: Deploy Dev
    environment: dev
    steps:
      - run: echo "Deploy Dev"

  deploy_prod:
    runs-on: ubuntu-latest
    if: contains(github.ref, 'tags')
    needs: ["build", "deploy_dev"]
    name: Deploy Prod
    environment: prod
    steps:
      - run: echo "Deploy Prod"
