name: Build & Deploy

on:
  push:
    branches:
      - "main"
    tags:
      - "v*"

jobs:
  deploy-new:
    name: deploy-new
    runs-on: ubuntu-latest
    environment: new
    steps:
      - run: env
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - uses: actions/github-script@v7
        id: previous-deploy
        with:
          result-encoding: string
          retries: 3
          script: |
            console.log(context.repo.owner);
            console.log(context.repo.repo);
            console.log(context.ref_name);
            
            const {data} = await github.rest.repos.listDeployments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: context.ref_name,
              environment: "new",
            });

            console.log(data);

            return data.at(1) || "f4749d7f252b1d0f275811c5ebc9020dc73d11ab";
      - run: |
          echo "previous: ${{ steps.previous-deploy.outputs.result }}"
        
