name: Build & Deploy

on:
  push:
    branches:
      - "main"
    tags:
      - "v*"

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest
    steps:
      - run: env
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"

  deploy-new:
    name: deploy-new
    runs-on: ubuntu-latest
    environment: new
    steps:
      - uses: actions/github-script@v7
        id: get-last-deploy
        with:
          result-encoding: string
          retries: 3
          script: |
            const {data} = await github.rest.repos.listDeployments({
              owner: "fabsrc",
              repo: "sandbox",
              environment: "new",
              ref: "main"
            });
            console.log(data.at(0));
            console.log(data.at(1));
            console.log(data.at(1) || "f4749d7f252b1d0f275811c5ebc9020dc73d11ab")
      - run: echo "Deploy to new"
